apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: healthmed
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080  # <- alterado conforme porta do container
      nodePort: 30854
  type: NodePort
