apiVersion: v1
kind: Service
metadata:
  name: api-patient-service
  namespace: healthmed
spec:
  selector:
    app: api-patient
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30855
  type: NodePort