apiVersion: v1
kind: Service
metadata:
  name: api-doctor-service
  namespace: healthmed
spec:
  selector:
    app: api-doctor
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30853
  type: NodePort