apiVersion: v1
kind: ConfigMap
metadata:
  name: api-patient-config
  namespace: healthmed
data:
  ASPNETCORE_ENVIRONMENT: Production
  DATABASE_URL: "Server=postgres-service;Port=5432;Database=HealthMed;User Id=admin;Password=;"
  API_KEY: "KJNJKBJHBSHJVJHJVDHBHSLSHUBUJNOSSSOLWSSDSGVHGDJHVHGFH"