apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: healthmed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway-service
          image: parmezao/health-med:HealthMed.Gateway.API-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: ConnectionStrings__postgres
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_CONNECTION
          envFrom:
            - configMapRef:
                name: api-gateway-config
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3