apiVersion: v1
kind: Service
metadata:
  name: api-agenda-service
  namespace: healthmed
spec:
  selector:
    app: api-agenda
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30850
  type: NodePort