apiVersion: v1
kind: Service
metadata:
  name: infra-consumer-doctor-service
  namespace: healthmed
spec:
  selector:
    app: infra-consumer-doctor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30901
  type: NodePort