apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-consumer-agenda
  namespace: healthmed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-consumer-agenda
  template:
    metadata:
      labels:
        app: infra-consumer-agenda
    spec:
      containers:
        - name: rabbitmq-consumer-agenda
          image: parmezao/health-med:HealthMed.Agenda.Infra.Consumer-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__postgres
              value: "Server=postgres-service;Port=5432;Database=HealthMed;User Id=admin;Password=$(POSTGRES_PASSWORD);"            
          envFrom:
            - configMapRef:
                name: infra-consumer-agenda-config
            - secretRef:
                name: postgres-secret                
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"