apiVersion: v1
kind: Service
metadata:
  name: infra-consumer-agenda-service
  namespace: healthmed
spec:
  selector:
    app: infra-agenda-agenda
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30904
  type: NodePort