apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-consumer-patient
  namespace: healthmed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-consumer-patient
  template:
    metadata:
      labels:
        app: infra-consumer-patient
    spec:
      containers:
        - name: rabbitmq-consumer-paciente
          image: parmezao/health-med:HealthMed.Patient.Infra.Consumer-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: infra-consumer-patient-config
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"