apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: healthmed
type: Opaque
stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "admin"
  POSTGRES_DB: "HealthMed"
  POSTGRES_CONNECTION: "Server=postgres-service;Port=5432;Database=HealthMed;User Id=admin;Password=admin"