apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: healthmed
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30097
  selector:
    app: prometheus