apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: healthmed
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'api-auth'
        static_configs:
          - targets: ['apiauth:8080']

      - job_name: 'api-patient'
        static_configs:
          - targets: ['apipac:8080']

      - job_name: 'api-doctor'
        static_configs:
          - targets: ['apimed:8080']

      - job_name: 'api-consultation'
        static_configs:
          - targets: ['apicon:8080']

      - job_name: 'api-agenda'
        static_configs:
          - targets: ['apiage:8080']

      - job_name: 'api-gateway'
        static_configs:
          - targets: ['apigateway:8080']

      - job_name: 'consumer-consultation'
        static_configs:
          - targets: ['rabbitmq-consumer-consulta:8080']

      - job_name: 'consumer-patient'
        static_configs:
          - targets: ['rabbitmq-consumer-paciente:8080']

      - job_name: 'consumer-doctor'
        static_configs:
          - targets: ['rabbitmq-consumer-medico:8080']

      - job_name: 'consumer-agenda'
        static_configs:
          - targets: ['rabbitmq-consumer-agenda:8080']

      - job_name: 'rabbitmq'
        static_configs:
          - targets: ['rabbitmq:15692']
