apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: healthmed
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/prometheus"
