# Usar a imagem oficial do PostgreSQL como base
FROM postgres:latest

# Definir as variáveis de ambiente padrão
ENV POSTGRES_DB=tech_challenge
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin

# Copiar o script de inicialização para a pasta padrão do PostgreSQL
COPY script.sql /docker-entrypoint-initdb.d/

# Expor a porta padrão do PostgreSQL
EXPOSE 5432
